### ISSUE TITLE
What a horrific mess of a code. Good intention to make this code available but make sure to mention this in the read me

### ISSUE THREAD

**Issue by JaeDukSeo** [h3lio5/linguistic-style-transfer-pytorch#10]
broken everywhere, good intention to make this code available but make sure to mention this in the read me

**Comment by sharan21** [comment]
This is for all people who are trying to replicate this paper in pytorch. This repo is hopelessly broken, even after fixing all bugs there are still severe implementation oversights and training is impossible. Kudos to the author for starting this initiative but please do not waste your time here.

We are attempting to build another implementation of this paper in pytorch and it is nearing completion. https://github.com/sharan21/disentangled-style-transfer-vae

Please feel free to improve this repo and contribute. Thanks to @h3lio5 for still providing support and functions to work with. :)
